/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaStoreIdIndexRouteImport } from './routes/loja.$storeId.index'
import { Route as LojaStoreIdVendedoraRepIdIndexRouteImport } from './routes/loja.$storeId.vendedora.$repId.index'
import { Route as LojaStoreIdVendedoraRepIdNaoVendeuRouteImport } from './routes/loja.$storeId.vendedora.$repId.nao-vendeu'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaStoreIdIndexRoute = LojaStoreIdIndexRouteImport.update({
  id: '/loja/$storeId/',
  path: '/loja/$storeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaStoreIdVendedoraRepIdIndexRoute =
  LojaStoreIdVendedoraRepIdIndexRouteImport.update({
    id: '/loja/$storeId/vendedora/$repId/',
    path: '/loja/$storeId/vendedora/$repId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LojaStoreIdVendedoraRepIdNaoVendeuRoute =
  LojaStoreIdVendedoraRepIdNaoVendeuRouteImport.update({
    id: '/loja/$storeId/vendedora/$repId/nao-vendeu',
    path: '/loja/$storeId/vendedora/$repId/nao-vendeu',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/loja/$storeId/': typeof LojaStoreIdIndexRoute
  '/loja/$storeId/vendedora/$repId/nao-vendeu': typeof LojaStoreIdVendedoraRepIdNaoVendeuRoute
  '/loja/$storeId/vendedora/$repId/': typeof LojaStoreIdVendedoraRepIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/loja/$storeId': typeof LojaStoreIdIndexRoute
  '/loja/$storeId/vendedora/$repId/nao-vendeu': typeof LojaStoreIdVendedoraRepIdNaoVendeuRoute
  '/loja/$storeId/vendedora/$repId': typeof LojaStoreIdVendedoraRepIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/loja/$storeId/': typeof LojaStoreIdIndexRoute
  '/loja/$storeId/vendedora/$repId/nao-vendeu': typeof LojaStoreIdVendedoraRepIdNaoVendeuRoute
  '/loja/$storeId/vendedora/$repId/': typeof LojaStoreIdVendedoraRepIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/loja/$storeId/'
    | '/loja/$storeId/vendedora/$repId/nao-vendeu'
    | '/loja/$storeId/vendedora/$repId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/loja/$storeId'
    | '/loja/$storeId/vendedora/$repId/nao-vendeu'
    | '/loja/$storeId/vendedora/$repId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/loja/$storeId/'
    | '/loja/$storeId/vendedora/$repId/nao-vendeu'
    | '/loja/$storeId/vendedora/$repId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LojaStoreIdIndexRoute: typeof LojaStoreIdIndexRoute
  LojaStoreIdVendedoraRepIdNaoVendeuRoute: typeof LojaStoreIdVendedoraRepIdNaoVendeuRoute
  LojaStoreIdVendedoraRepIdIndexRoute: typeof LojaStoreIdVendedoraRepIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$storeId/': {
      id: '/loja/$storeId/'
      path: '/loja/$storeId'
      fullPath: '/loja/$storeId/'
      preLoaderRoute: typeof LojaStoreIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$storeId/vendedora/$repId/': {
      id: '/loja/$storeId/vendedora/$repId/'
      path: '/loja/$storeId/vendedora/$repId'
      fullPath: '/loja/$storeId/vendedora/$repId/'
      preLoaderRoute: typeof LojaStoreIdVendedoraRepIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$storeId/vendedora/$repId/nao-vendeu': {
      id: '/loja/$storeId/vendedora/$repId/nao-vendeu'
      path: '/loja/$storeId/vendedora/$repId/nao-vendeu'
      fullPath: '/loja/$storeId/vendedora/$repId/nao-vendeu'
      preLoaderRoute: typeof LojaStoreIdVendedoraRepIdNaoVendeuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LojaStoreIdIndexRoute: LojaStoreIdIndexRoute,
  LojaStoreIdVendedoraRepIdNaoVendeuRoute:
    LojaStoreIdVendedoraRepIdNaoVendeuRoute,
  LojaStoreIdVendedoraRepIdIndexRoute: LojaStoreIdVendedoraRepIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
